language: python
python:
  - 3.7
env:
  global:
  - secure: XOeEf27Sx/bPqK7Bj0QmLC5XXXfmyjFvO/7mvCpKYWvEOZ4tOQOP0uvBEkedB3E2iuaoSuhC7gfnxSyM/TXTMmrQx5sNqUidAsfXVGg90OZs6MwfaqiVImHs5xdztlQWs4wPx9sDll+JygF12r9ZmDaDkIE9rcALZeCdCN4AY9GSEI4uF06UIqyhgecWO6P/r8BvUUjG+kDd9axbjxPaWKjyA5G/nQnxZ4s89XWeQqmGMBwNJYP6tBscriyj6YG8QH+5gPbiqrk6xO1/RZKR54huwtphzVFvA7311V3DKyQnp6twHrohxq+DDcZGDt3TzcHTU73EgUtmbtLsHtG+QCkIdpAMpp7XyVAos3O2tmceBUtLfcjVD36ZvCIV69v9CBI5v0HZqYVDYxt45+oPWOBs8X5S6p2Qi35+KkNfzYTKL8XXVZNjgTxD27YkkPwPArDSKRNOOCGGrrcGJykDaSKfKRPxb6DK7I99bdL9cnXRPMrEigndxJ6OtjSwRA05kljNIiRAuqY6rhIbjUYhzLGTjqxci+avcTUiYhQUz+Lf2ES4fDNrPs960bEoEveUYoMTL8PuQTrrqU1qhMwrNs/1FdGNCkPbIfQ50t3wHlYfmYrxdgPApyjNlD3pzEvig6X6WmizBpj/bthDRNwgw0xf7OQqeZ6RNI2e3VYSvXg=
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8 autocsr tests
  - poetry run pytest tests
before_deploy:
  - poetry build
  - poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
