language: python
python:
  - 3.7
  - 3.8
  - 3.9
env:
  global:
  - secure: WijUap0H0tg8lHM6Vy9UvABQdf+6LXbd1FRIjsSdBcjgxkLrq7JtCGOeCW6NVVL9nLdFdTrxk5IeI7Owj+0hVe91a+rEZpWCG9oX1vVSMwMULwYDKOnFyJabBuF4N+LP6VyJk90UYy4iuj1Uf0F/YzfD//pMS//s4bJsTP//fSoO3b3HSkViPIvHBwr7QizxNtf5djkIC90JZ3hl9w4vQO7jQabfsbCT9zXRMLtpEd5pb0uU4VQTLBqpHM/pDgWM2BDKXBzD21ZbmaT+kAiS1F0xBt3UN8dTcgINvDw7Zs2kLO1qMmckFM4kBV60gQ3nbWiB+WJiBm5IFnwKb3jUFGhscrWNR1rfo1mTU4ZxDdulC4+Gnnabt0S2Q8BgXSgT3+F81OIze0mEZQXMoNIlI1Yg3RfC3IuAWYrc4Hcul+UCEw1tyP+vUZCuEMMQ5aPE2qLHK3idZkoA2aFm0EKz7+7qfJGLSoBtEyO3FvNdmMmV9wK1ynSIO0DzaeJaiARU+FOm9qaFpXxkhX1TdoeZv8AP4zgtXPfHs3PsU9YcETZUvhlQOJ6IXWsqyoRdCWZ6YFOknMRplfpEkBwGtvFnoHM5tmjPiWfxBkN4uiOLMr5Hd7Ljig6qUsaPA71NHTWM9SBED7axDO6lgTacfO1mNZqJexJcgEpJ7ypjJmdu8lc=
  - secure: Llj56kz2Cfu0JiFeC8s9jGpjWma0qLmHePUdzaqm27XqD1eheLCOfmiHi8gTf0dNpplCQBmJvAarNdne6yTYWNexNZbAqfJyWkKvONkmQTLtn4HWIMx/DeuIuqiv9biQWyYnfOfCE48U75q+A/BDTs2wJlrX3WQLGtpeHkKyYP3rqJWQroEQJVOf1xQ3Efs9vsG+llVsqoDGcA/8KjAaeadsVwEkrmuY6yp2MxK9vUO4HHprvgpOL9fsZm4Ccxzi0bULmaHWMJARrQg7bczZT0t1kzxuHJPHTuPCtwBjc3imvsAGy6Xh+fKBukC+hufgUAfkzYg4II0jn6AkMSQG3vhxkB0FRTrdMGNQty8YBp9h1dWcuJi4FouCDVvA6rZqv1m/HXmzgNRxEpr5Ar8mIjkfMgFHBCXNP8z9YHzPF6f0tNdEvYpbp56WGbNKBc0nhBq9+5ygt/RMsOBEJeTymnh3E+jaeKxgu5tBZ4V7iJ0oLWNQLhMaT3+uQ127iNMmfnI3es1/CykOb5x4ujvjp1Si2hj6+x6Hv3eMFytJh8j13+BFPELU7nLhDyIoGMgDjLYM3kdNLUHuXgpkuTHmzQTq7JDrT7uJnxvJxD+6+p+06mJqEv8D8VkN+xz18MmMNRiNZcfe5q72NtBKu89SlPbY8DAO/Me+ErA6PuK2r34=
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8 autocsr tests
  - poetry run pytest tests
before_deploy:
  - poetry build
  - poetry config repositories.pypi https://pypi.org/simple
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
deploy:
  provider: script
  script: poetry publish -r pypi
  skip_cleanup: true
  on:
    tags: true
